# Generated by Django 2.1.5 on 2020-05-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyNetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
